### ISSUE TITLE
Statement is incorrect

### ISSUE THREAD

**Issue by ericdebleumortier** [atulrnt/le-if-qui-fait-tout#1]
The if is not working 👎 

OS: Gameboy Color
RAM: Yes
Storage: True
Version: 6.9

**Comment by atulrnt** [comment]
Sorry, the Gameboy Color is only supported from version version 7, please consider updating to a more recent version.

**Comment by ericdebleumortier** [comment]
Ok thanks for the fast answer! I'll update that!
